<a href="https://colab.research.google.com/github/vitorchaud/calc_num/blob/main/Gauss_Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cálculo Numérico para a Engenheria Elétrica (CALNE) 2S - 2025**

---

# **Método de Gauss-Seidel**
---



In [1]:
# Importa a biblioteca NumPy para manipulação de matrizes e vetores
import numpy as np

# Define a matriz A e o vetor b do sistema Ax = b
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)

# Define o número de variáveis do sistema
n = len(b)

# Define o vetor inicial de aproximações x, inicialmente com zeros
x = np.zeros(n)

# Define a tolerância para o critério de parada
tolerancia = 1e-10

# Define o número máximo de iterações
max_iteracoes = 10

# Iteração do método de Gauss-Seidel
for iteracao in range(max_iteracoes):
    # Cria uma cópia do vetor x para verificar o critério de parada posteriormente
    x_anterior = np.copy(x)

    print(x_anterior)

    # Para cada variável xi
    for i in range(n):
        # Calcula a soma dos produtos A[i][j] * x[j] para j ≠ i
        soma = 0
        for j in range(n):
            if j != i:
                soma += A[i][j] * x[j]

        # Atualiza o valor de xi usando os valores mais recentes disponíveis
        x[i] = (b[i] - soma) / A[i][i]

    # Verifica o critério de parada com base na diferença entre x e x_anterior
    if np.allclose(x, x_anterior, atol=tolerancia):
        print(f"Convergência alcançada após {iteracao + 1} iterações.")
        break
else:
    print("Número máximo de iterações atingido sem convergência.")

# Exibe a solução aproximada
print("Solução aproximada:")
print(x)


[0. 0. 0. 0.]
[3.75     3.4375   3.359375 4.453125]
[4.609375   4.4921875  4.73632812 4.91210938]
[4.87304688 4.90234375 4.95361328 4.98453776]
[4.97558594 4.9822998  4.99170939 4.99723646]
[4.99557495 4.99682109 4.99851439 4.9995048 ]
[4.99920527 4.99942991 4.99973368 4.99991123]
[4.99985748 4.99989779 4.99995225 4.99998408]
[4.99997445 4.99998168 4.99999144 4.99999715]
Convergência alcançada após 9 iterações.
Solução aproximada:
[4.99999542 4.99999671 4.99999847 4.99999949]
