<a href="https://colab.research.google.com/github/vitorchaud/calc_num/blob/main/Gauss_Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cálculo Numérico para a Engenheria Elétrica (CALNE) 2S - 2025**

---

# **Método de Gauss-Seidel**
---



In [2]:
# Importa a biblioteca NumPy para manipulação de matrizes e vetores
import numpy as np

# Define a matriz A e o vetor b do sistema Ax = b
'''
A = np.array([[4, -1, 1],
              [4, -8, 1],
              [-2, 1, 5]], dtype=float)

b = np.array([7, -21, 15], dtype=float)
'''

A = np.array([[-2, 1, 5],
              [4, -8, 1],
              [4, -1, 1]], dtype=float)

b = np.array([7, -21, 15], dtype=float)

'''
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)
'''
# Define o número de variáveis do sistema
n = len(b)

# Define o vetor inicial de aproximações x, inicialmente com zeros
x = np.zeros(n)

# Define a tolerância para o critério de parada
tolerancia = 1e-10

# Define o número máximo de iterações
max_iteracoes = 10

# Iteração do método de Gauss-Seidel
for iteracao in range(max_iteracoes):
    # Cria uma cópia do vetor x para verificar o critério de parada posteriormente
    x_anterior = np.copy(x)

    print(x_anterior)

    # Para cada variável xi
    for i in range(n):
        # Calcula a soma dos produtos A[i][j] * x[j] para j ≠ i
        soma = 0
        for j in range(n):
            if j != i:
                soma += A[i][j] * x[j]

        # Atualiza o valor de xi usando os valores mais recentes disponíveis
        x[i] = (b[i] - soma) / A[i][i]

    # Verifica o critério de parada com base na diferença entre x e x_anterior
    if np.allclose(x, x_anterior, atol=tolerancia):
        print(f"Convergência alcançada após {iteracao + 1} iterações.")
        break
else:
    print("Número máximo de iterações atingido sem convergência.")

# Exibe a solução aproximada
print("Solução aproximada:")
print(x)


[0. 0. 0.]
[-3.5    0.875 29.875]
[  71.625      42.171875 -229.328125]
[-555.734375   -303.90820312 1934.02929688]
[  4679.61914062   2584.18823242 -16119.28833008]
[-39009.62670898 -21517.09939575 134536.40744019]
[  325578.96890259   179609.16038132 -1122691.71522903]
[-2716928.20788193 -1498797.94334459  9368929.88818312]
[ 22672922.2487855   12507579.98541564 -78184094.00972635]
[-1.89206449e+08 -1.04376233e+08  6.52449576e+08]
Número máximo de iterações atingido sem convergência.
Solução aproximada:
[ 1.57893582e+09  8.71024109e+08 -5.44471915e+09]
