<a href="https://colab.research.google.com/github/vitorchaud/calc_num/blob/main/M%C3%A9todo_de_Jacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cálculo Numérico para a Engenheria Elétrica (CALNE) 2S - 2025**

---

# **Método de Jacobi**
---



In [4]:
# Importa a biblioteca NumPy para manipulação de matrizes e vetores
import numpy as np

# Define a matriz A e o vetor b do sistema Ax = b
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]], dtype=float)

b = np.array([15, 10, 10, 10], dtype=float)

# Define o número de variáveis do sistema
n = len(b)

# Define o vetor inicial de aproximações x, inicialmente com zeros
x = np.zeros(n)

# Define a tolerância para o critério de parada
tolerancia = 1e-10

# Define o número máximo de iterações
max_iteracoes = 10

# Iteração do método de Jacobi
for iteracao in range(max_iteracoes):
    # Cria uma cópia do vetor x para armazenar os novos valores
    x_novo = np.copy(x)

    print(x_novo)

    # Para cada variável xi
    for i in range(n):
        # Calcula a soma dos produtos A[i][j] * x[j] para j ≠ i
        soma = 0
        for j in range(n):
            if j != i:
                soma += A[i][j] * x[j]

        # Atualiza o valor de xi
        x_novo[i] = (b[i] - soma) / A[i][i]

    # Verifica o critério de parada com base na diferença entre x_novo e x
    if np.allclose(x, x_novo, atol=tolerancia):
        break

    # Atualiza o vetor x para a próxima iteração
    x = x_novo

# Exibe a solução aproximada
print("Solução aproximada:")
print(x)




[0. 0. 0. 0.]
[3.75       2.5        2.5        3.33333333]
[4.375      4.0625     3.95833333 4.16666667]
[4.765625   4.58333333 4.55729167 4.65277778]
[4.89583333 4.83072917 4.80902778 4.85243056]
[4.95768229 4.92621528 4.92078993 4.93634259]
[4.98155382 4.96961806 4.96563947 4.97359664]
[4.99240451 4.98679832 4.98580367 4.98854649]
[4.99669958 4.99455205 4.9938362  4.99526789]
[4.99863801 4.99763395 4.99745498 4.9979454 ]
Solução aproximada:
[4.99940849 4.99902325 4.99889484 4.99915166]
